### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by rszamszur** [fastapi-mvc/fastapi-mvc#54]
Hello there! :wave:

The project is in the early stages of development, hence the documentation can be chaotic, incomplete, or hard to follow. Also if I'm being honest I'm not very good at explaining stuff :sweat_smile:. Feel free to raise an issue or PR if something is missing, unclear, or wrong.

## Current issues:

- [x] fastapi-mvc/fastapi-mvc#9 
   - [x] Init mkdocs documentation with base contents fastapi-mvc/fastapi-mvc#33
- [x] fastapi-mvc/fastapi-mvc#74
- [ ] fastapi-mvc/fastapi-mvc#177 
- [x] fastapi-mvc/fastapi-mvc#75
